// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rxnksyeitnxwevscxfbg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4bmtzeWVpdG54d2V2c2N4ZmJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NjExMDEsImV4cCI6MjA2NDQzNzEwMX0.cCe2rUyu1xtLXXG-IyA34m3Tq59hK1e4dDutKT8G13c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);